baseURL = "https://storeios.net"
languageCode = "vi-vn"
title = "storeios"

[params]
  disqusShortname = "storeios"

[markup.goldmark.renderer]
  unsafe = true

[build]
  publishDir = "public"
  minify = true
  gc = true

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  apps = "/apps/:slug/"
  jailbreak-tools = "/jailbreak/:slug/"
  categories = "/categories/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "JSON"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true

# Thêm phần này để xử lý URL tiếng Việt
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]