baseURL = "https://storeios.net"
languageCode = "vi-vn"
title = "storeios"
# Comment out the theme line
# theme = "ananke"

[params]
  # Các tham số tùy chỉnh

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20

[markup.goldmark.renderer]
  unsafe = true