baseURL = "https://storeios.net"
languageCode = "vi-vn"
title = "storeios"
# Uncomment this line if you have a theme to use
# theme = "ananke"
[params]
  # Các tham số tùy chỉnh nếu cần
  disqusShortname = "storeios"
# Bỏ cấu hình menu không cần thiết
[markup.goldmark.renderer]
  unsafe = true
# Thêm cấu hình build nếu cần
[build]
  publishDir = "public"
  minify = true
  gc = true
[permalinks]
  posts = "/:slug/"
  apps = "/:slug/"
  jailbreak-tools = "/:slug/"
  categories = "/categories/:slug/"
[taxonomies]
category = "categories"
tag = "tags"
[outputs]
  home = ["HTML", "JSON"]
[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true