[build]
  publish = "public"
  command = "hugo --gc --minify"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "16"

[[edge_functions]]
  function = "block"
  path = "/*"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/shortener/*"
  to = "/.netlify/functions/shorten/"
  status = 200

[[redirects]]
  from = "/download"
  to = "/.netlify/functions/download"
  status = 200

[[redirects]]
  from = "/:shortId"
  to = "/.netlify/functions/redirect/:shortId"
  status = 200

[context.ipadl]
  [[redirects]]
    from = "/"
    to = "/ipa-downloader.html"
    status = 200
    force = true

[[redirects]]
  from = "/ipa-downloader.html"
  to = "https://ipadl.storeios.net"
  status = 301
  force = true
  
[dev]
  framework = "hugo"
  targetPort = 1313

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"