[build]
  publish = "public"
  command = "hugo --gc --minify"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/shortener/*"
  to = "/.netlify/functions/shorten/"
  status = 200

[[redirects]]
  from = "/download"
  to = "/.netlify/functions/download"
  status = 200

[[redirects]]
  from = "/:shortId"
  to = "/.netlify/functions/redirect/:shortId"
  status = 200

 [[redirects]]
  from = "/plist/index.html"
  to = "/.netlify/functions/block-access"
  status = 302
  force = true

[[redirects]]
  from = "/plist/*"
  to = "/.netlify/functions/block-access"
  status = 302
  force = true

  
[dev]
  framework = "hugo"
  targetPort = 1313

[[headers]]
  for = "/upload"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    