[build]
  publish = "public"
  command = "hugo --gc --minify"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/shortener/*"
  to = "/.netlify/functions/shorten/"
  status = 200

[[redirects]]
  from = "/:shortId"
  to = "/.netlify/functions/redirect"
  status = 200

[dev]
  framework = "hugo"
  targetPort = 1313