[build]
  publish = "public"
  command = "hugo --gc --minify"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]
  
[build.environment]
  NODE_VERSION = "16"
  GO_VERSION = "1.17"
  
[build.lifecycle]
onBuild = """
  npm install -g ipatool
  ipatool --version
"""

[[edge_functions]]
  function = "block"
  path = "/*"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/shortener/*"
  to = "/.netlify/functions/shorten/"
  status = 200

[[redirects]]
  from = "/download"
  to = "/.netlify/functions/download"
  status = 200

[[redirects]]
  from = "/:shortId"
  to = "/.netlify/functions/redirect/:shortId"
  status = 200

[[headers]]
  for = "/*.plist"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/plist/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'none'"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[dev]
  framework = "hugo"
  targetPort = 1313