[functions]
  directory = "netlify/functions"
  included_files = ["content/**"]

[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200