backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "category"
    label: "Chuyên mục"
    folder: "content/apps"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tên chuyên mục", name: "title", widget: "string"}
      - {label: "Mô tả", name: "description", widget: "text"}

  - name: "app"
    label: "Ứng dụng"
    folder: "content/apps"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tên ứng dụng", name: "title", widget: "string"}
      - {label: "Ngày đăng", name: "date", widget: "datetime"}
      - {label: "Ảnh icon", name: "icon", widget: "image"}
      - {label: "Ảnh screenshot", name: "screenshots", widget: "list", field: {label: Ảnh, name: image, widget: image}}
      - {label: "Mô tả ngắn", name: "short_description", widget: "text"}
      - {label: "Mô tả chi tiết", name: "description", widget: "markdown"}
      - {label: "Nhà phát triển", name: "developer", widget: "string"}
      - {label: "Thể loại", name: "category", widget: "select", options: ["Ứng dụng", "Games", "Tool jailbreak", "Thủ thuật", "File ipa", "Khác"]}
      - {label: "Chuyên mục", name: "categories", widget: "relation", collection: "category", search_fields: ["title"], value_field: "title", multiple: true}
      
      - {label: "Phiên bản", name: "version", widget: "string"}
      - {label: "Kích thước", name: "size", widget: "string"}
      - {label: "iOS tương thích", name: "requirements", widget: "string"}
      - {label: "Ngôn ngữ hỗ trợ", name: "languages", widget: "list"}
      - {label: "Liên kết tải App Store", name: "app_store_link", widget: "string"}
      - {label: "Từ khóa", name: "tags", widget: "list"}