backend:
  name: git-gateway
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Ngày đăng", name: "date", widget: "datetime"}
      - {label: "Tác giả", name: "author", widget: "string"}
      - {label: "Số lượt xem", name: "views", widget: "number"}
      - {label: "Hình ảnh đại diện", name: "thumbnail", widget: "image", required: false}
      - {label: "Mô tả ngắn", name: "description", widget: "text", required: false}
      - {label: "Nội dung", name: "body", widget: "markdown"}
      - {label: "Thẻ", name: "tags", widget: "list", required: false}
      - {label: "Chuyên mục", name: "categories", widget: "list", required: false}

  - name: "app"
    label: "Ứng dụng"
    folder: "content/apps"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tên ứng dụng", name: "title", widget: "string", required: true}
      - {label: "Ngày đăng", name: "date", widget: "datetime", required: true}
      - {label: "Ảnh icon", name: "icon", widget: "image", required: true}
      - {label: "Ảnh screenshot", name: "screenshots", widget: "list", field: {label: "Ảnh", name: "image", widget: "image"}, required: false}
      - {label: "Mô tả ngắn", name: "short_description", widget: "text", required: false}
      - {label: "Mô tả chi tiết", name: "description", widget: "markdown", required: true}
      - {label: "Nhà phát triển", name: "developer", widget: "string", required: true}
      - {label: "Thể loại", name: "category", widget: "select", options: ["Ứng dụng", "Games", "Tool jailbreak", "Thủ thuật", "File ipa", "Khác"], required: true}
      - {label: "Chuyên mục", name: "categories", widget: "relation", collection: "category", search_fields: ["title"], value_field: "title", multiple: true, required: true}
      - {label: "Phiên bản", name: "version", widget: "string", required: true}
      - {label: "Kích thước", name: "size", widget: "string", required: true}
      - {label: "iOS tương thích", name: "requirements", widget: "string", required: true}
      - {label: "Ngôn ngữ hỗ trợ", name: "languages", widget: "list", required: true}
      - {label: "Liên kết tải App Store", name: "app_store_link", widget: "string", required: true}
      - {label: "Từ khóa", name: "tags", widget: "list", required: false}

  - name: "category"
    label: "Chuyên mục"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tên chuyên mục", name: "title", widget: "string", required: true}
      - {label: "Mô tả", name: "description", widget: "text", required: true}

  - name: "jailbreak-tools"
    label: "Tool Jailbreak"
    folder: "content/jailbreak-tools"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tên Tool", name: "title", widget: "string", required: true}
      - {label: "Ngày đăng", name: "date", widget: "datetime", required: true}
      - {label: "Icon", name: "icon", widget: "image", required: true}
      - {label: "Ảnh màn hình", name: "screenshots", widget: "list", field: {label: "Ảnh", name: "image", widget: "image"}, required: false}
      - {label: "Mô tả ngắn", name: "short_description", widget: "text", required: false}
      - {label: "Mô tả chi tiết", name: "description", widget: "markdown", required: true}
      - {label: "Nhà phát triển", name: "developer", widget: "string", required: true}
      - {label: "Thể loại", name: "category", widget: "string", required: true}
      - {label: "Kích thước", name: "size", widget: "string", required: true}
      - {label: "iOS tương thích", name: "ios_compatible", widget: "string", required: true}
      - {label: "Từ khóa", name: "keywords", widget: "list", required: false}
      - {name: "versions", label: "Versions", widget: "list", fields: [
          {name: "version", label: "Version", widget: "string"},
          {name: "appId", label: "App ID", widget: "string"},
          {name: "plistUrl", label: "Plist URL", widget: "string", hint: "Nhập URL đầy đủ đến file .plist, ví dụ: https://storeios.net/plist/unc0ver.plist"},
          {name: "intermediate_page_url", label: "Intermediate Page URL", widget: "text", default: "/intermediate/:appId"}
        ]}
load_config_file: false
local_backend: true
publish_mode: editorial_workflow

cms_manual_init: true
custom_css: /css/admin.css