backend:
  name: git-gateway
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title | urlize}}"
    fields:
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Ngày đăng", name: "date", widget: "datetime"}
      - {label: "Tác giả", name: "author", widget: "string"}
      - {label: "Hình ảnh đại diện", name: "thumbnail", widget: "image", required: false}
      - {label: "Mô tả ngắn", name: "description", widget: "text", required: false}
      - {label: "Nội dung", name: "body", widget: "markdown"}
      - {label: "Thẻ", name: "tags", widget: "list", required: false}
      - {label: "Chuyên mục", name: "categories", widget: "list", required: false}

  - name: "app"
    label: "Ứng dụng"
    folder: "content/apps"
    create: true
    slug: "{{slug}}-{{title | urlize}}"
    fields:
      - {label: "Tên ứng dụng", name: "title", widget: "string", required: true}
      - {label: "Ngày đăng", name: "date", widget: "datetime", required: true}
      - {label: "Ảnh icon", name: "icon", widget: "image", required: true}
      - {label: "Ảnh screenshot", name: "screenshots", widget: "list", field: {label: "Ảnh", name: "image", widget: "image"}, required: false}
      - {label: "Mô tả ngắn", name: "short_description", widget: "text", required: false}
      - {label: "Mô tả chi tiết", name: "description", widget: "markdown", required: true}
      - {label: "Nhà phát triển", name: "developer", widget: "string", required: true}
      - {label: "Thể loại", name: "category", widget: "select", options: ["Ứng dụng", "Games", "Tool jailbreak", "Thủ thuật", "File ipa", "Khác"], required: true}
      - {label: "Phiên bản", name: "version", widget: "string", required: true}
      - {label: "Kích thước", name: "size", widget: "string", required: true}
      - {label: "iOS tương thích", name: "requirements", widget: "string", required: true}
      - {label: "Ngôn ngữ hỗ trợ", name: "languages", widget: "list", required: true}
      - {label: "Liên kết tải App Store", name: "app_store_link", widget: "string", required: true}
      - {label: "Từ khóa", name: "tags", widget: "list", required: false}

  - name: "jailbreak-tools"
    label: "Tool Jailbreak"
    folder: "content/jailbreak-tools"
    create: true
    slug: "{{slug}}-{{title | urlize}}"
    fields:
      - {label: "Tên Tool", name: "title", widget: "string", required: true}
      - {label: "Ngày đăng", name: "date", widget: "datetime", required: true}
      - {label: "Icon", name: "icon", widget: "image", required: true}
      - {label: "Ảnh màn hình", name: "screenshots", widget: "list", field: {label: "Ảnh", name: "image", widget: "image"}, required: false}
      - {label: "Mô tả ngắn", name: "short_description", widget: "text", required: false}
      - {label: "Mô tả chi tiết", name: "description", widget: "markdown", required: true}
      - {label: "Nhà phát triển", name: "developer", widget: "string", required: true}
      - {label: "Thể loại", name: "categories", widget: "string", required: true}
      - {label: "Kích thước", name: "size", widget: "update-size", required: false}  # Trường kích thước
      - {label: "iOS tương thích", name: "ios_compatible", widget: "string", required: true}
      - {label: "Từ khóa", name: "keywords", widget: "list", required: false}
      - name: "main_download"
        label: "Liên kết tải xuống chính"
        widget: "object"
        fields:
          - {name: "version", label: "Phiên bản", widget: "string"}
          - {name: "appId", label: "App ID", widget: "string"}
          - {name: "plistUrl", label: "Plist URL", widget: "string", hint: "Nhập URL đầy đủ đến file .plist, ví dụ: https://storeios.net/plist/unc0ver.plist"}
      - name: "other_versions"
        label: "Các phiên bản khác"
        widget: "list"
        fields:
          - {name: "version", label: "Phiên bản", widget: "string"}
          - {name: "appId", label: "App ID", widget: "string"}
          - {name: "plistUrl", label: "Plist URL", widget: "string", hint: "Nhập URL đầy đủ đến file .plist"}

cms_manual_init: true
custom_css: /css/admin.css
custom_widgets:
  - name: update-size
    file: "/admin/widgets/updateSize.js"