backend:
  name: github
  repo: chienlove/chienlove.github.io
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "apps"  # Tên collection, sử dụng cho API và URL
    label: "Thông tin ứng dụng iOS"  # Nhãn hiển thị trong CMS
    folder: "content/apps"  # Thư mục lưu trữ nội dung
    create: true  # Cho phép tạo mới bài viết
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "hidden", default: "{{year}}{{month}}{{day}}{{slug}}" }
      - { label: "Tên ứng dụng", name: "appName", widget: "string" }
      - { label: "Phiên bản ứng dụng", name: "appVersion", widget: "string" }
      - { label: "Nhà phát triển", name: "developer", widget: "string" }
      - { label: "Mô tả ứng dụng", name: "description", widget: "text" }
      - { label: "Ảnh màn hình ứng dụng", name: "appImages", widget: "list", fields: [
          { label: "Ảnh màn hình", name: "image", widget: "image" }
        ] }
      - { label: "Phiên bản iOS tương thích", name: "iosCompatibility", widget: "string" }
      - { label: "Liên kết tải ứng dụng", name: "downloadLink", widget: "string" }
      - { label: "Chuyên mục", name: "category", widget: "select", options: [
          { label: "Chưa phân loại", value: "uncategorized" },
          { label: "Tin tức", value: "news" },
          { label: "Mẹo hay", value: "tips" },
          { label: "Cập nhật", value: "updates" }
        ] }