backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "apps"
    label: "Thông tin ứng dụng iOS"
    folder: "content/apps"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Tên ứng dụng", name: "appName", widget: "string"}
      - {label: "Mô tả ứng dụng", name: "description", widget: "text"}