backend:
  name: github
  repo: chienlove/chienlove.github.io
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow
site_url: https://yourdomain.com
display_url: https://yourdomain.com
logo_url: https://yourdomain.com/images/logo.png
locale: 'vi'

collections:
  - name: "apps"
    label: "Ứng dụng"
    folder: "content/apps"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Nội dung", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Trang"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Nội dung", name: "body", widget: "markdown"}