backend:
  name: github
  repo: chienlove/chienlove.github.io
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}

  - name: "apps"
    label: "Apps"
    folder: "content/apps"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "App Name", name: "app_name", widget: "string"}
      - {label: "App Image", name: "app_image", widget: "image"}
      - {label: "App Description", name: "app_description", widget: "text"}
      - {label: "Developer", name: "developer", widget: "string"}
      - {label: "iOS Version Compatibility", name: "ios_version", widget: "string"}
      - {label: "App Version", name: "app_version", widget: "string"}
      - {label: "Download Link", name: "download_link", widget: "string"}
      - {label: "Category", name: "category", widget: "relation", collection: "categories", searchFields: ["name"], valueField: "name", displayFields: ["name"]}
      - {label: "Body", name: "body", widget: "markdown"}