backend:
  name: git-gateway
  branch: master

media_folder: "public/assets/guides-img"
public_folder: "/assets/guides-img"
collections: 
  - name: "guide"
    label: "guides"
    folder: "src/guide"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" } 
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["guides"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
   - name: "pages"
    label: "page"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" } 
      - { label: "Body", name: "body", widget: "markdown" }