backend:
  name: github
  repo: chienlove/chienlove.github.io
  branch: master
base_url: https://api.netlify.com

# Cài đặt chung
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
display_url: https://storeios.net
logo_url: https://storeios.net/images/logo.png
site_url: https://storeios.net
locale: 'vi'
show_preview_links: true

collections:
  - name: "apps"
    label: "Ứng dụng"
    folder: "content/apps"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Ngày đăng", name: "date", widget: "datetime"}
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "app"}
      - {label: "Mô tả ngắn", name: "description", widget: "text"}
      - label: "Hình ảnh"
        name: "image"
        widget: "object"
        fields:
          - {label: "Alt Text", name: "alt", widget: "string"}
          - {label: "URL", name: "url", widget: "image"}
      - {label: "Tên ứng dụng", name: "appName", widget: "string"}
      - {label: "Phiên bản", name: "version", widget: "string"}
      - {label: "Kích thước", name: "size", widget: "string"}
      - {label: "Nhà phát triển", name: "developer", widget: "string"}
      - {label: "Thể loại", name: "category", widget: "select", options: ["Game", "Công cụ", "Giáo dục", "Giải trí", "Khác"]}
      - {label: "Giá", name: "price", widget: "string", default: "Miễn phí"}
      - {label: "Link tải", name: "downloadLink", widget: "string"}
      - {label: "Nội dung chi tiết", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Trang"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Nội dung", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Cài đặt"
    files:
      - file: "content/settings/general.md"
        label: "Cài đặt chung"
        name: "general"
        fields:
          - {label: "Tên trang web", name: "siteName", widget: "string"}
          - {label: "Mô tả trang web", name: "siteDescription", widget: "text"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Favicon", name: "favicon", widget: "image"}