backend:
  name: github
  branch: main
  repo: chienlove/chienlove.github.io
  auth_endpoint: auth
  base_url: api.netlify.com
  squash_merges: true

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "Blog posts"
    folder: "content/posts"
    extension: md
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Show TOC", name: "showToc", widget: "boolean", default: true}
      - {label: "Draft", name: "draft", widget: "boolean", required: false, default: false}
      - {label: "Description", name: "description", widget: "string", required: false}
      - widget: object
        name: cover
        label: Cover
        required: false
        fields:
          - {label: Image, name: image, widget: string, required: false, comment: image path/url}
          - {label: Alt, name: alt, widget: string, required: false, comment: alt text}
          - {label: Caption, name: caption, widget: string, required: false, comment: display caption under cover}
          - {label: Relative, name: relative, widget: string, required: false, comment: when using page bundles set this to true}
          - {label: Hidden, name: hidden, widget: "hidden", required: false, default: false, comment: only hide on current single page}
      - {label: "Body", name: "body", widget: "markdown"}

      publish_mode: editorial_workflow  # Bật chế độ quy trình biên tập

site_url: https://storeios.netlify.app  # URL của trang web bạn trên Netlify
logo_url: https://storeios.net/CydiaIcon.png  # URL logo của trang web bạn

display_url: https://storeios.netlify.app  # URL hiển thị cho CMS
      
