baseURL = "https://chienlove.github.io"
languageCode = "en-us"
title = "storeios"

# Comment out the theme line
# theme = "ananke"

# Các cài đặt khác có thể được thêm vào đây
[params]
  # Các tham số tùy chỉnh

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20

# Thêm các cấu hình khác nếu cần