[build]
command = "npm install && npm run build"
publish = "build"

[dev]
command = "node server.js"
port = 3000

[[redirects]]
from = "/api/*"
to = "http://localhost:5004/:splat"
status = 200
force = true