name = "ipa-downloader"
account_id = "$CF_ACCOUNT_ID"
workers_dev = true
main = "src/index.js"
compatibility_date = "2024-07-31"
node_compat = true

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "ipa-downloads"

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
external = ["jszip", "node"]