- name: Publish Cloudflare Worker
  env:
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  run: |
    cd ipa-downloader
    # Cập nhật account_id trong wrangler.toml
    sed -i 's/account_id = "$CF_ACCOUNT_ID"/account_id = "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"/g' wrangler.toml
    # In nội dung của wrangler.toml để kiểm tra
    cat wrangler.toml
    # Cài đặt dependencies nếu cần
    npm install
    # Deploy worker
    wrangler deploy