name: Build iOS Bypass ScreenCapture Dylib (Custom App)

on:
  workflow_dispatch:
    inputs:
      app_bundle_id:
        description: "Nhập CFBundleIdentifier của app (ví dụ: com.spotify.client)"
        required: true
        default: "com.overseas.tandoo"  # Đã di chuyển default value vào đúng vị trí

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          # Install dependencies
          brew install dpkg ldid xz make
          brew upgrade make || true
          
          # Setup Theos
          sudo rm -rf /opt/theos 2>/dev/null || true
          sudo mkdir -p /opt/theos
          sudo chown -R $USER:admin /opt/theos
          sudo chmod -R 755 /opt/theos
          
          export THEOS=/opt/theos
          git clone --recursive --depth 1 https://github.com/theos/theos.git $THEOS
          
          # Setup SDKs
          mkdir -p $THEOS/sdks
          cd $THEOS/sdks
          wget https://github.com/theos/sdks/archive/refs/heads/master.zip -O sdks.zip
          unzip -q sdks.zip
          mv sdks-master/* .
          rm -rf sdks-master sdks.zip
          
          LATEST_SDK=$(ls -d iPhoneOS*.sdk | sort -V | tail -1)
          ln -sf "$LATEST_SDK" iPhoneOS.sdk
          echo "✅ Using SDK: $LATEST_SDK"

      - name: Create Tweak project
        run: |
          export THEOS=/opt/theos
          mkdir -p TweakProject
          
          # Tweak.x - Core bypass logic
          cat > TweakProject/Tweak.x << 'EOL'
          #import <UIKit/UIKit.h>
          
          // Hook chính để bypass screen capture
          %hook UIScreen
          - (BOOL)isCaptured { return NO; }
          %end
          
          %hook UIView
          - (BOOL)_shouldPreventScreenCapture { return NO; }
          %end
          
          // Hook thêm cho các phương thức bảo vệ tuỳ chỉnh
          %hook SBApplication
          - (BOOL)hasProtectionForScreenCapture { return NO; }
          %end
          
          __attribute__((constructor)) static void init() {
              NSLog(@"[Bypass] Dylib injected vào bundle: ${{ github.event.inputs.app_bundle_id }}");
          }
          EOL
          
          # Filter.plist - Target app bundle ID
          cat > TweakProject/BypassScreenCapture.plist << EOL
          { 
              Filter = { 
                  Bundles = ( 
                      "${{ github.event.inputs.app_bundle_id }}",
                      "com.apple.UIKit" 
                  ); 
              }; 
          }
          EOL
          
          # Makefile
          cat > TweakProject/Makefile << 'EOL'
          ARCHS = arm64 arm64e
          TARGET = iphone:latest
          include $(THEOS)/makefiles/common.mk
          
          TWEAK_NAME = BypassScreenCapture
          BypassScreenCapture_FILES = Tweak.x
          BypassScreenCapture_CFLAGS = -fobjc-arc
          
          include $(THEOS_MAKE_PATH)/tweak.mk
          
          after-install::
          	install.exec "killall -9 SpringBoard"
          EOL
          
          # control file
          mkdir -p TweakProject/layout/DEBIAN
          cat > TweakProject/layout/DEBIAN/control << EOL
          Package: com.yourcompany.bypass
          Name: BypassScreenCapture for ${{ github.event.inputs.app_bundle_id }}
          Version: 1.0-1
          Architecture: iphoneos-arm
          Description: Disable screen capture protections for specific app
          Maintainer: YourName
          Author: YourName
          Section: Tweaks
          EOL

      - name: Build tweak
        run: |
          export THEOS=/opt/theos
          cd TweakProject
          
          # Fix permissions and build
          find . -type f -exec chmod 644 {} \;
          find . -type d -exec chmod 755 {} \;
          
          export THEOS_MAKE_PARALLEL=yes
          make clean
          make package
          
          # Extract dylib
          cp .theos/obj/debug/BypassScreenCapture.dylib ../BypassScreenCapture.dylib || \
          (mkdir -p pkg && dpkg-deb -R packages/*.deb pkg && \
          cp pkg/Library/MobileSubstrate/DynamicLibraries/*.dylib ../BypassScreenCapture.dylib)

      - name: Verify and upload artifacts
        run: |
          if [ -f "BypassScreenCapture.dylib" ]; then
              echo "✅ Build thành công cho bundle ID: ${{ github.event.inputs.app_bundle_id }}"
              file BypassScreenCapture.dylib
          else
              echo "❌ Build thất bại!"
              exit 1
          fi
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BypassScreenCapture_${{ github.event.inputs.app_bundle_id }}
          path: |
            BypassScreenCapture.dylib
            TweakProject/packages/*.deb