name: Build iOS Bypass ScreenCapture Dylib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Theos (Ultimate Version)
        run: |
          # Clean previous installations
          sudo rm -rf /opt/theos 2>/dev/null || true
          
          # Setup directories with proper permissions
          sudo mkdir -p /opt/theos
          sudo chown -R $USER:admin /opt/theos
          sudo chmod -R 755 /opt/theos
          
          # Install Theos
          export THEOS=/opt/theos
          git clone --recursive --depth 1 https://github.com/theos/theos.git $THEOS
          
          # Install dependencies
          xcode-select --install || true
          brew install ldid xz make
          brew upgrade make || true
          
          # Setup SDKs
          mkdir -p $THEOS/sdks
          cd $THEOS/sdks
          wget https://github.com/theos/sdks/archive/refs/heads/master.zip -O sdks.zip
          unzip -q sdks.zip
          mv sdks-master/* .
          rm -rf sdks-master sdks.zip
          
          # Find and link latest SDK
          LATEST_SDK=$(ls -d iPhoneOS*.sdk | sort -V | tail -1)
          if [ -n "$LATEST_SDK" ]; then
              ln -sf "$LATEST_SDK" iPhoneOS.sdk
              echo "✅ Using SDK: $LATEST_SDK"
          else
              echo "❌ Error: No SDK found"
              ls -la
              exit 1
          fi

      - name: Create complete Tweak project
        run: |
          export THEOS=/opt/theos
          mkdir -p TweakProject
          
          # Create Tweak.x
          cat > TweakProject/Tweak.x << 'EOL'
          #import <UIKit/UIKit.h>
          
          %hook UIScreen
          - (BOOL)isCaptured { return NO; }
          %end
          
          %hook UIView
          - (BOOL)_shouldPreventScreenCapture { return NO; }
          %end
          
          __attribute__((constructor)) static void init() {
              NSLog(@"[Bypass] Dylib injected!");
          }
          EOL
          
          # Create Filter.plist
          cat > TweakProject/BypassScreenCapture.plist << 'EOL'
          { Filter = { Bundles = ( "com.apple.springboard" ); }; }
          EOL
          
          # Create control file (ESSENTIAL for packaging)
          mkdir -p TweakProject/layout/DEBIAN
          cat > TweakProject/layout/DEBIAN/control << 'EOL'
          Package: com.yourcompany.bypassscreencapture
          Name: BypassScreenCapture
          Version: 1.0
          Architecture: iphoneos-arm
          Description: Disable screen capture protection
          Maintainer: YourName
          Author: YourName
          Section: Tweaks
          EOL
          
          # Create Makefile with parallel building
          cat > TweakProject/Makefile << 'EOL'
          ARCHS = arm64 arm64e
          TARGET = iphone:latest
          include $(THEOS)/makefiles/common.mk
          TWEAK_NAME = BypassScreenCapture
          BypassScreenCapture_FILES = Tweak.x
          BypassScreenCapture_CFLAGS = -fobjc-arc
          include $(THEOS_MAKE_PATH)/tweak.mk
          
          after-install::
              install.exec "killall -9 SpringBoard"
          EOL

      - name: Build and package tweak
        run: |
          export THEOS=/opt/theos
          cd TweakProject
          
          # Enable parallel building
          export THEOS_MAKE_PARALLEL=yes
          
          # Clean and build
          make clean
          make package
          
          # Extract the dylib from the package
          mkdir -p pkg
          dpkg-deb -R packages/*.deb pkg
          cp pkg/Library/MobileSubstrate/DynamicLibraries/*.dylib ../BypassScreenCapture.dylib
          
          # Verify the output
          if [ -f "../BypassScreenCapture.dylib" ]; then
              echo "✅ Build successful!"
              file "../BypassScreenCapture.dylib"
          else
              echo "❌ Error: Failed to build dylib"
              exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BypassScreenCapture
          path: |
            BypassScreenCapture.dylib
            TweakProject/packages/*.deb