name: Build iOS Bypass ScreenCapture Dylib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Theos (Final Fix)
        run: |
          # Cài đặt Theos
          export THEOS=/opt/theos
          sudo rm -rf $THEOS 2>/dev/null || true
          git clone --recursive https://github.com/theos/theos.git $THEOS
          
          # Cài đặt dependencies
          xcode-select --install || true
          brew install ldid xz
          
          # Tải SDK từ repo riêng (đã kiểm tra tồn tại)
          sudo mkdir -p $THEOS/sdks
          cd $THEOS/sdks
          sudo wget https://github.com/theos/sdks/archive/master.zip -O sdks.zip
          sudo unzip -q sdks.zip
          sudo mv sdks-master/* .
          sudo rm -rf sdks-master sdks.zip
          
          # Tạo symlink cho SDK
          if [ -d "iPhoneOS16.0.sdk" ]; then
              sudo ln -s iPhoneOS16.0.sdk iPhoneOS.sdk
              echo "✅ SDK đã được thiết lập:"
              ls -la
          else
              echo "❌ Lỗi: Không tìm thấy SDK"
              ls -la
              exit 1
          fi

      - name: Create Tweak project
        run: |
          export THEOS=/opt/theos
          mkdir -p TweakProject
          cat > TweakProject/Tweak.x << 'EOL'
          #import <UIKit/UIKit.h>
          
          %hook UIScreen
          - (BOOL)isCaptured { return NO; }
          %end
          
          %hook UIView
          - (BOOL)_shouldPreventScreenCapture { return NO; }
          %end
          
          __attribute__((constructor)) static void init() {
              NSLog(@"[Bypass] Dylib injected!");
          }
          EOL
          
          cat > TweakProject/Makefile << 'EOL'
          ARCHS = arm64 arm64e
          TARGET = iphone:latest
          include $(THEOS)/makefiles/common.mk
          TWEAK_NAME = BypassScreenCapture
          BypassScreenCapture_FILES = Tweak.x
          include $(THEOS_MAKE_PATH)/tweak.mk
          EOL

      - name: Build dylib
        run: |
          export THEOS=/opt/theos
          cd TweakProject && make clean && make package
          cp .theos/obj/debug/*.dylib ../BypassScreenCapture.dylib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BypassScreenCapture.dylib
          path: BypassScreenCapture.dylib