name: Build iOS Bypass ScreenCapture Dylib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          # Install dpkg and other required tools
          brew install dpkg
          brew install ldid xz make
          brew upgrade make || true
          
          # Setup Theos
          sudo rm -rf /opt/theos 2>/dev/null || true
          sudo mkdir -p /opt/theos
          sudo chown -R $USER:admin /opt/theos
          sudo chmod -R 755 /opt/theos
          
          export THEOS=/opt/theos
          git clone --recursive --depth 1 https://github.com/theos/theos.git $THEOS
          
          # Setup SDKs
          mkdir -p $THEOS/sdks
          cd $THEOS/sdks
          wget https://github.com/theos/sdks/archive/refs/heads/master.zip -O sdks.zip
          unzip -q sdks.zip
          mv sdks-master/* .
          rm -rf sdks-master sdks.zip
          
          LATEST_SDK=$(ls -d iPhoneOS*.sdk | sort -V | tail -1)
          ln -sf "$LATEST_SDK" iPhoneOS.sdk
          echo "✅ Using SDK: $LATEST_SDK"

      - name: Create Tweak project
        run: |
          export THEOS=/opt/theos
          mkdir -p TweakProject
          
          # Tweak.x
          cat > TweakProject/Tweak.x << 'EOL'
          #import <UIKit/UIKit.h>
          
          %hook UIScreen
          - (BOOL)isCaptured { return NO; }
          %end
          
          %hook UIView
          - (BOOL)_shouldPreventScreenCapture { return NO; }
          %end
          
          __attribute__((constructor)) static void init() {
              NSLog(@"[Bypass] Dylib injected!");
          }
          EOL
          
          # Filter.plist
          cat > TweakProject/BypassScreenCapture.plist << 'EOL'
          { Filter = { Bundles = ( "com.apple.springboard" ); }; }
          EOL
          
          # Makefile (with proper tabs)
          cat > TweakProject/Makefile << 'EOL'
          ARCHS = arm64 arm64e
          TARGET = iphone:latest
          include $(THEOS)/makefiles/common.mk
          
          TWEAK_NAME = BypassScreenCapture
          BypassScreenCapture_FILES = Tweak.x
          BypassScreenCapture_CFLAGS = -fobjc-arc
          
          include $(THEOS_MAKE_PATH)/tweak.mk
          
          after-install::
          	install.exec "killall -9 SpringBoard"
          EOL
          
          # control file
          mkdir -p TweakProject/layout/DEBIAN
          cat > TweakProject/layout/DEBIAN/control << 'EOL'
          Package: com.yourcompany.bypass
          Name: BypassScreenCapture
          Version: 1.0-1
          Architecture: iphoneos-arm
          Description: Disable screen capture protections
          Maintainer: YourName
          Author: YourName
          Section: Tweaks
          EOL

      - name: Build tweak
        run: |
          export THEOS=/opt/theos
          cd TweakProject
          
          # Fix line endings and permissions
          dos2unix Makefile 2>/dev/null || true
          find . -type f -exec chmod 644 {} \;
          find . -type d -exec chmod 755 {} \;
          
          # Build with parallel processing
          export THEOS_MAKE_PARALLEL=yes
          make clean
          make package
          
          # Extract dylib directly from .theos build
          cp .theos/obj/debug/BypassScreenCapture.dylib ../BypassScreenCapture.dylib
          
          if [ -f "../BypassScreenCapture.dylib" ]; then
              echo "✅ Build successful!"
              file "../BypassScreenCapture.dylib"
              ls -la ../BypassScreenCapture.dylib
          else
              echo "❌ Build failed - trying alternative method..."
              # Fallback method to extract from deb
              mkdir -p pkg
              dpkg-deb -R packages/*.deb pkg 2>/dev/null || true
              cp pkg/Library/MobileSubstrate/DynamicLibraries/*.dylib ../BypassScreenCapture.dylib || true
              
              if [ -f "../BypassScreenCapture.dylib" ]; then
                  echo "✅ Fallback extraction successful"
              else
                  echo "❌ All build methods failed"
                  exit 1
              fi
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BypassScreenCapture
          path: |
            BypassScreenCapture.dylib
            TweakProject/packages/*.deb