name: Build iOS Bypass ScreenCapture Dylib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Theos (Fixed)
        run: |
          # Cài đặt Theos từ bản release 2.4
          export THEOS=/opt/theos
          sudo rm -rf $THEOS 2>/dev/null || true
          wget https://github.com/theos/theos/archive/refs/tags/2.4.zip -O /tmp/theos.zip
          sudo unzip -q /tmp/theos.zip -d /tmp/
          sudo mv /tmp/theos-2.4 $THEOS
          
          # Cài đặt dependencies
          xcode-select --install || true
          brew install ldid xz
          
          # Xóa thư mục sdks cũ (nếu có) và clone mới
          sudo rm -rf $THEOS/sdks 2>/dev/null || true
          sudo mkdir -p $THEOS/sdks
          sudo git clone https://github.com/theos/sdks.git $THEOS/sdks --depth=1
          
          # Kiểm tra và tạo symlink
          if [ -d "$THEOS/sdks/iPhoneOS.sdk" ]; then
              echo "✅ SDK đã được tải thành công"
              ls -la $THEOS/sdks/
          else
              echo "❌ Lỗi: Không tìm thấy SDK"
              exit 1
          fi

      - name: Create Tweak project
        run: |
          export THEOS=/opt/theos
          mkdir -p TweakProject
          cat > TweakProject/Tweak.x << 'EOL'
          #import <UIKit/UIKit.h>
          
          %hook UIScreen
          - (BOOL)isCaptured { return NO; }
          %end
          
          %hook UIView
          - (BOOL)_shouldPreventScreenCapture { return NO; }
          %end
          
          __attribute__((constructor)) static void init() {
              NSLog(@"[Bypass] Dylib injected!");
          }
          EOL
          
          cat > TweakProject/Makefile << 'EOL'
          ARCHS = arm64 arm64e
          TARGET = iphone:latest
          include $(THEOS)/makefiles/common.mk
          TWEAK_NAME = BypassScreenCapture
          BypassScreenCapture_FILES = Tweak.x
          include $(THEOS_MAKE_PATH)/tweak.mk
          EOL

      - name: Build dylib
        run: |
          export THEOS=/opt/theos
          cd TweakProject && make clean && make package
          cp .theos/obj/debug/*.dylib ../BypassScreenCapture.dylib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BypassScreenCapture.dylib
          path: BypassScreenCapture.dylib