name: Build iOS Bypass ScreenCapture Dylib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Theos
        run: |
          # Tạo và cấp quyền thư mục Theos
          sudo mkdir -p /opt/theos
          sudo chown -R $USER:admin /opt/theos
          sudo chmod -R 755 /opt/theos
          
          # Cài đặt Theos
          export THEOS=/opt/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          
          # Cài đặt dependencies
          xcode-select --install || true
          brew install ldid xz
          
          # Tải và cài đặt SDK
          mkdir -p $THEOS/sdks
          cd $THEOS/sdks
          wget https://github.com/theos/sdks/archive/refs/heads/master.zip -O sdks.zip
          unzip -q sdks.zip
          mv sdks-master/* .
          rm -rf sdks-master sdks.zip
          
          # Tạo symlink cho SDK mới nhất
          LATEST_SDK=$(ls -d iPhoneOS*.sdk | sort -V | tail -1)
          if [ -n "$LATEST_SDK" ]; then
              ln -s "$LATEST_SDK" iPhoneOS.sdk
              echo "✅ Đã chọn SDK: $LATEST_SDK"
          else
              echo "❌ Lỗi: Không tìm thấy bất kỳ SDK nào"
              ls -la
              exit 1
          fi

      - name: Create Tweak project
        run: |
          export THEOS=/opt/theos
          mkdir -p TweakProject
          
          # Tạo file Tweak.x
          cat > TweakProject/Tweak.x << 'EOL'
          #import <UIKit/UIKit.h>
          
          %hook UIScreen
          - (BOOL)isCaptured { return NO; }
          %end
          
          %hook UIView
          - (BOOL)_shouldPreventScreenCapture { return NO; }
          %end
          
          __attribute__((constructor)) static void init() {
              NSLog(@"[Bypass] Dylib injected!");
          }
          EOL
          
          # Tạo file Filter.plist (QUAN TRỌNG)
          cat > TweakProject/BypassScreenCapture.plist << 'EOL'
          { Filter = { Bundles = ( "com.apple.springboard" ); }; }
          EOL
          
          # Tạo Makefile
          cat > TweakProject/Makefile << 'EOL'
          ARCHS = arm64 arm64e
          TARGET = iphone:latest
          include $(THEOS)/makefiles/common.mk
          TWEAK_NAME = BypassScreenCapture
          BypassScreenCapture_FILES = Tweak.x
          include $(THEOS_MAKE_PATH)/tweak.mk
          EOL

      - name: Build dylib
        run: |
          export THEOS=/opt/theos
          cd TweakProject && make clean && make package
          cp .theos/obj/debug/*.dylib ../BypassScreenCapture.dylib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BypassScreenCapture.dylib
          path: BypassScreenCapture.dylib