name: Deploy Firebase Hosting (manual, only 2 files)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout (sparse: only 2 files)"
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            firebase.json
            public/index.html
          sparse-checkout-cone: false

      - name: "Sanity check"
        run: |
          ls -la
          echo "----- public -----"
          ls -la public

      - name: "Deploy to Firebase Hosting"
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: comments-storeios