name: Hugo build and deploy

on:
  push:
    branches:
      - master  # Thay đổi thành tên branch chính của bạn nếu khác

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Lấy Hugo themes (true OR recursive)
          fetch-depth: 0    # Lấy tất cả history cho .GitInfo và .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
