name: Deploy IPA Downloader

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Wrangler
      run: npm install -g wrangler

    - name: Deploy Worker
      run: |
        if [ -d "ipa-downloader" ]; then
          cd ipa-downloader
          wrangler publish
        else
          echo "ipa-downloader directory does not exist"
          exit 1
        fi
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
