name: Deploy IPA Downloader

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: install jszip
      run: npm install jszip

    - name: Install Wrangler
      run: npm install -g wrangler@latest

    - name: Create wrangler.toml with environment variables
      run: |
        if [ -d "ipa-downloader" ]; then
          cd ipa-downloader
          echo "name = \"ipa-downloader\"" > wrangler.toml
          echo "account_id = \"$CF_ACCOUNT_ID\"" >> wrangler.toml
          echo "workers_dev = true" >> wrangler.toml
          echo "main = \"src/index.js\"" >> wrangler.toml
          echo "compatibility_date = \"2024-07-31\"" >> wrangler.toml
          echo "" >> wrangler.toml
          echo "[[r2_buckets]]" >> wrangler.toml
          echo "binding = \"MY_BUCKET\"" >> wrangler.toml
          echo "bucket_name = \"ipa-downloads\"" >> wrangler.toml
        else
          echo "ipa-downloader directory does not exist"
          exit 1
        fi
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

    - name: Deploy Worker
      run: |
        if [ -d "ipa-downloader" ]; then
          cd ipa-downloader
          wrangler deploy
        else
          echo "ipa-downloader directory does not exist"
          exit 1
        fi
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
