name: Upload File to GitHub Release

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'Path to the file to upload'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install @octokit/rest

    - name: Run upload script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_REPOSITORY_NAME: ${{ github.repository }}
        FILE_PATH: ${{ github.event.inputs.file }}
      run: node js/upload.js
